In [2]:
from __future__ import print_function
import torch


# torch 기본 생성

In [10]:
# 초기화 되지 않은 행렬 생성
x = torch.empty(5,5)
print(x, x.dtype)

tensor([[0.7617, 0.3610, 0.4390, 0.1208, 0.5391],
        [0.1070, 0.5742, 0.7208, 0.8445, 0.2333],
        [0.1528, 0.4258, 0.0697, 0.4005, 0.6472],
        [0.3435, 0.6814, 0.3156, 0.8855, 0.4930],
        [0.3262, 0.4706, 0.8788, 0.8595, 0.1865]]) torch.float32


In [9]:
#  랜덤수로 초기화 된 행렬 생성, 기본적으로 float32 타입으로 생성
x = torch.rand(5,5)
print(x, x.dtype)

tensor([[0.4921, 0.8293, 0.8212, 0.0756, 0.2730],
        [0.9631, 0.1153, 0.6156, 0.2329, 0.0657],
        [0.4595, 0.9901, 0.0191, 0.1991, 0.2946],
        [0.0486, 0.2345, 0.5988, 0.3047, 0.8554],
        [0.8573, 0.2344, 0.1344, 0.3123, 0.5410]]) torch.float32


In [13]:
# data type을 long 형식으로 생성, long -> torch.int64, int -> torch.int32 ////// int16, int 32, int64
x = torch.zeros(5,5, dtype= torch.long)
print(x, x.dtype)


tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]) torch.int64


In [17]:
# data를 직접 집어넣어 텐서 생성 -> int64

x = torch.tensor([[5, 6, 7],[1,2,3]])
print(x, x.dtype)

tensor([[5, 6, 7],
        [1, 2, 3]]) torch.int64


In [21]:
# 사이즈를 받아서 값을 1로 생성 double -> float64
x = x.new_ones(5, 5, dtype = torch.double)
print(x)

## x의 사이즈 받아서 텐서 생성
x = torch.rand_like(x, dtype = torch.float)
print(x, x.dtype)


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[1.9789e-01, 6.8300e-01, 7.8244e-01, 7.5881e-01, 6.3583e-01],
        [6.7020e-01, 3.4224e-01, 3.5679e-01, 6.5374e-01, 2.1664e-01],
        [4.6754e-01, 3.5926e-01, 9.0216e-01, 9.4597e-02, 2.0020e-01],
        [4.1849e-01, 7.4751e-01, 1.3953e-04, 1.6600e-01, 2.6895e-01],
        [7.3840e-01, 3.1949e-01, 6.0653e-01, 6.9459e-01, 4.5781e-01]]) torch.float32


In [23]:
print(x.size())

torch.Size([5, 5])


In [32]:
## 텐서 연산도 가능

y = torch.rand(5,5)
print(y, y.dtype)
print("\n")
print(x+ y)
print("\n")
print(torch.add(x,y))

tensor([[0.7606, 0.1561, 0.0461, 0.5562, 0.1554],
        [0.7151, 0.7788, 0.7505, 0.0067, 0.7508],
        [0.1899, 0.9431, 0.4679, 0.1143, 0.3417],
        [0.0802, 0.5097, 0.8803, 0.8896, 0.0551],
        [0.6617, 0.8991, 0.2596, 0.0998, 0.4432]]) torch.float32


tensor([[0.9585, 0.8391, 0.8286, 1.3150, 0.7913],
        [1.3853, 1.1210, 1.1073, 0.6604, 0.9675],
        [0.6574, 1.3023, 1.3701, 0.2089, 0.5419],
        [0.4987, 1.2572, 0.8804, 1.0556, 0.3240],
        [1.4001, 1.2185, 0.8662, 0.7944, 0.9011]])


tensor([[0.9585, 0.8391, 0.8286, 1.3150, 0.7913],
        [1.3853, 1.1210, 1.1073, 0.6604, 0.9675],
        [0.6574, 1.3023, 1.3701, 0.2089, 0.5419],
        [0.4987, 1.2572, 0.8804, 1.0556, 0.3240],
        [1.4001, 1.2185, 0.8662, 0.7944, 0.9011]])


In [33]:
## 연산 결과를 인자로 output, but 빈 공간은 생선해놓아야함

result = torch.empty(5,5)
torch.add(x,y, out = result)
print(result)


tensor([[0.9585, 0.8391, 0.8286, 1.3150, 0.7913],
        [1.3853, 1.1210, 1.1073, 0.6604, 0.9675],
        [0.6574, 1.3023, 1.3701, 0.2089, 0.5419],
        [0.4987, 1.2572, 0.8804, 1.0556, 0.3240],
        [1.4001, 1.2185, 0.8662, 0.7944, 0.9011]])


In [34]:
## in_place 함수를 이용하여 연산 값으로 업데이트 할 수 있음
y.add_(x)
print(y)

tensor([[0.9585, 0.8391, 0.8286, 1.3150, 0.7913],
        [1.3853, 1.1210, 1.1073, 0.6604, 0.9675],
        [0.6574, 1.3023, 1.3701, 0.2089, 0.5419],
        [0.4987, 1.2572, 0.8804, 1.0556, 0.3240],
        [1.4001, 1.2185, 0.8662, 0.7944, 0.9011]])


In [36]:
## numpy 처럼 인덱싱 가능
print(y[:,3])

tensor([1.3150, 0.6604, 0.2089, 1.0556, 0.7944])


In [39]:
## torch.view로  tensor의 resize/ reshape가능

y1 = y.view(25)
y2 = y.view(-1,25) ## -1로 차원 유지

print(y1, y1.size())
print("\n")
print(y2, y2.size())

tensor([0.9585, 0.8391, 0.8286, 1.3150, 0.7913, 1.3853, 1.1210, 1.1073, 0.6604,
        0.9675, 0.6574, 1.3023, 1.3701, 0.2089, 0.5419, 0.4987, 1.2572, 0.8804,
        1.0556, 0.3240, 1.4001, 1.2185, 0.8662, 0.7944, 0.9011]) torch.Size([25])


tensor([[0.9585, 0.8391, 0.8286, 1.3150, 0.7913, 1.3853, 1.1210, 1.1073, 0.6604,
         0.9675, 0.6574, 1.3023, 1.3701, 0.2089, 0.5419, 0.4987, 1.2572, 0.8804,
         1.0556, 0.3240, 1.4001, 1.2185, 0.8662, 0.7944, 0.9011]]) torch.Size([1, 25])


In [47]:
## item() 으로 텐서의 숫자값을 가져올 수 있음 
## torch.rand vs torch.randn -> randn의 경우 표준 정규분포를 따르는 랜덤 값을 반환함
x1 = torch.randn(3)
print(x1)
print(x1[1].item())

tensor([0.7100, 0.3168, 1.6223])
0.3168359696865082


# torch와 numpy 호환 생성

In [48]:
import numpy as np

In [54]:
## torch -> numpy , 
x = torch.ones(2,2)
print(x, x.dtype)
print("\n")
x1 = x.numpy()
print(x1, x1.dtype)

tensor([[1., 1.],
        [1., 1.]]) torch.float32


[[1. 1.]
 [1. 1.]] float32


In [55]:
## torch가 cpu라면 numpy array와 메모리 공간을 공유 -> 충격적..

x.add_(3)
print(x)
print("\n")
print(x1)

tensor([[4., 4.],
        [4., 4.]])


[[4. 4.]
 [4. 4.]]


In [60]:
# numpy array -> tensor, 역시나 numpy에 연산해도 tensor도 같이 바뀜, 메모리를 공유하기 때문
y = np.ones((2,2))
print(y)
print("\n")
y1 = torch.from_numpy(y)
print(y1)
np.add(y, 1, out= y)
print(y)
print(y1)

[[1. 1.]
 [1. 1.]]


tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
[[2. 2.]
 [2. 2.]]
tensor([[2., 2.],
        [2., 2.]], dtype=torch.float64)


In [ ]:
'''
만약 cuda gpu가 있다면 다음 코드도 가능

# .to를 사용하여 객체를 장치로 이동시킬 수 있음

if torch.cuda.is_available():
    device_gpu = torch.device("cuda") ## cuda 장치 객체 생성
    y = torch.ones_like(y1, device = device_gpu)
    y = y.to(device_gpu)

    z = x + y
    print(z)
    print(z.to("cpu",torch.double))

'''